# Note: USE_SYSTEM_PERL does not work, some
# modules are missing in the repos (Sereal, Plack::Test)

language: perl

matrix:
  include:
## XXX not ready, see above
#    - perl: "5.14"
#      env: USE_SYSTEM_PERL=1
    - perl: "5.30"
      dist: xenial
# IPv6 address of www.cpan.org is currently slow --- use another mirror instead
    - perl: "5.20"
      env: PERL_CPANM_OPT="--mirror http://cpan.cpantesters.org --mirror https://cpan.metacpan.org"
      dist: trusty
    - perl: "5.18"
      dist: trusty
    - perl: "5.14"
      dist: trusty
    - perl: "5.10"
      dist: precise

before_install:
 - '[ "`lsb_release -cs`" = "precise" ] && sudo rm -f /etc/apt/sources.list.d/mongodb.list || true'
 - '[ "$USE_SYSTEM_PERL"  = "1" ] && perlbrew off || true'
 - sudo apt-get update -qq
 - sudo apt-get install -qq wget
# additional repo for Sereal etc.
 - '[ "$USE_SYSTEM_PERL"  = "1" ] && sudo chown travis /etc/apt/sources.list.d && echo "deb http://mydebs.bbbike.de precise main" > /etc/apt/sources.list.d/mydebs.bbbike.list || true'
 - '[ "$USE_SYSTEM_PERL"  = "1" ] && wget -O- http://mydebs.bbbike.de/key/mydebs.bbbike.key | sudo apt-key add - || true'
# 02packages.details.txt.gz should be fetched via cronjob or so
 - mkdir -p /tmp/.cpan/sources/modules
 - (cd /tmp/.cpan/sources/modules && wget https://cpan.metacpan.org/modules/02packages.details.txt.gz)
# only needed for plack.t
 - '[ "$USE_SYSTEM_PERL"  = "1" ] && sudo apt-get install -qq libimage-info-perl libplack-perl libcgi-emulate-psgi-perl libcgi-compile-perl || true'
 - '[ "$USE_SYSTEM_PERL" != "1" ] && cpanm --quiet --notest Image::Info Plack::Test CGI::Emulate::PSGI CGI::Compile || true'
# optional, by default Storable is used
 - '[ "$USE_SYSTEM_PERL"  = "1" ] && sudo apt-get install -qq libsereal-encoder-perl libseareal-decoder-perl || true'
 - '[ "$USE_SYSTEM_PERL" != "1" ] && cpanm --quiet --notest Sereal::Encoder Sereal::Decoder || true'

install:
 - '[ "$USE_SYSTEM_PERL"  = "1" ] && sudo apt-get install -qq libcpan-distnameinfo-perl libgravatar-url-perl libhtml-table-perl libwww-perl liburi-query-perl libjson-xs-perl libyaml-syck-perl || true'
 - '[ "$USE_SYSTEM_PERL" != "1" ] && cpanm --quiet --notest --installdeps . || true'

before_script:
 - (cd cgi-bin && ln -s cpantestersmatrix.yml.travis cpantestersmatrix.yml)
# fix shebang for plackup operation
 - (cd cgi-bin && env PERL=$(which perl) perl -pe '$_ = "#!$ENV{PERL} -T\n" if $. == 1' cpantestersmatrix.pl > cpantestersmatrix-travis.pl && chmod 755 cpantestersmatrix-travis.pl)

script:
  - perl Makefile.PL && env HARNESS_TIMER=1 HARNESS_OPTIONS=j4:c make test
# Don't use "make disttest" here; we need the changes done in before_script

branches:
 except:
  - /appveyor/
